### ISSUE TITLE
Jibri doesn't seem to be there

### ISSUE THREAD

**Issue by nukulyadav** [jelastic-jps/jitsi#14]
Hi,

For high end uses, I've following questions :

1. Can you add it with K8s (preconfigured) for high load uses ? or HELM can be provided. 
2. Jibri Cluster and Jiconfo doesn't seem to be integrated.

I'm already using it on a Jelastic provider, but looking for these things (specifically Jibri Cluster) at the earliest for deployment.

My project is already in final dev stage.

**Comment by sych74** [comment]
> Can you add it with K8s (preconfigured) for high load uses ? or HELM can be provided.

It seems like Jitsi in K8s is a [quite premature yet](https://github.com/jitsi/docker-jitsi-meet/blob/master/examples/kubernetes/README.md). Also, if properly configured, Jelastic can scale any middleware stacks w/o the need to use K8s. 

> Jibri Cluster and Jiconfo doesn't seem to be integrated.


How did you make this conclusion? 

> I'm already using it on a Jelastic provider, but looking for these things (specifically Jibri Cluster) at the earliest for deployment.

Configuration and customization of Jitsi for highly loaded projects are considered as a custom work at the moment as there is [no an easy option to set it up out-of-box](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-scalable). If you are interested in such customization please send your requirements and description of the project details to <a href="mailto:info@jelastic.com">info@jelastic.com</a>. After that our team will be able to estimate the required amount of efforts and provide the cost estimation together with possible delivery timeline.

**Comment by nukulyadav** [comment]
Jibri Cluster and Jiconfo doesn't seem to be integrated.

How did you make this conclusion? - Because I did deployed the Jitsi from here, but Jibri and Jiconfo aren't installed with it.

You may check this 

http://prntscr.com/tz0bdb


Thanks

**Comment by sych74** [comment]
You mention that "there is no option to record". Do you see the button "Start recording"?

![image](https://user-images.githubusercontent.com/17590698/90144119-12906d80-dd87-11ea-89ac-6aec71f0bc4b.png)

**Comment by nukulyadav** [comment]
Oops, I missed it so badly, can't trust my eyes anymore. Moreover my Hoster team also missed it and told me Jibri can't be installed as it needs a specific Kernel version.

Anyway, thanks for updating me.

I've 2 questions:

1. Can the admin credentials setup be disabled ? 
2. If Jibri on Jelastic is recording a session (session 1), can it record session 2 simultaneously ?

**Comment by sych74** [comment]
> my Hoster team also missed it and told me Jibri can't be installed as it needs a specific Kernel version.

It's true. Which one provider do you use? I believe we updated the majority pf partners for enabling recording feature. 

> Can the admin credentials setup be disabled ?

Yes, it can be disabled. Why do you need it? What is the case? 

> If Jibri on Jelastic is recording a session (session 1), can it record session 2 simultaneously ?

At the moment only one concurrent session is configured. More concurrent sessions are possible, but an additional customization is required.

**Comment by nukulyadav** [comment]
Update on Jibri - http://prntscr.com/tz18j3

It's not working

**Comment by sych74** [comment]
Please  answer questions in my previous thread.

**Comment by nukulyadav** [comment]
Yes, it can be disabled. Why do you need it? What is the case? - We are working to build a commercial solution with Jitsi as a base, which would be deployed on Jelastic.

Therefore we would have a situation where multiple users using it at the same time, so we need to disable the default admin/user thing. Please suggest how we can do that?

On Jibri front also - as said, we would have multiple people using it, we would want Jibri1+3 standby Jibri (dynamically) to scale and record incoming sessions on request. What customization is needed, please advise so we can enable it. Ideally this would have been nice in default setup as this actually fits into "Scaling feature of Jelastic".

**Comment by sych74** [comment]
Ok, I see. If you want to go with a commercial solution based on Jitsi then you definitely need to get familiar with Jitsi fine tuning and configurations or hire somebody who can do the job for you. There are two main resources to start with 
https://community.jitsi.org/ and https://github.com/jitsi. Disabling admin authentication is a simple task. Please dive deeper and come back when you have more complex questions. 

Btw, you have not provided the name of your service provider. We will check why the recording option is not enabled yet.

**Comment by nukulyadav** [comment]
Ok, thanks. We have React devs on-board. I went through fine tuning and it's fine.

Not getting idea on disabling the admin authentication. Could you guide please?

http://prntscr.com/tz2qfd - Service provider. I don't want to defame/name them in public. I would deleted this after I've your acknowledgement.

**Comment by sych74** [comment]
>  I don't want to defame/name them in public

What's the problem to give some visibility to your provider?  

> I would deleted this after I've your acknowledgement.

OK, I got the name, we will check.  

> Not getting idea on disabling the admin authentication. Could you guide please?

Sorry, but you need to do some research.

**Comment by nukulyadav** [comment]
Alright. Would you be considering making standby provisioning for Jibri in your package ?

Without the standby Jibri pool, it's actually useless for most of the users because any installation is likely to have more than 1 session for recording going on in 90%+ scenarios.

**Comment by sych74** [comment]
> Would you be considering making standby provisioning for Jibri in your package ? Without the standby Jibri pool, it's actually useless for most of the users because any installation is likely to have more than 1 session for recording going on in 90%+ scenarios.

At the moment it sounds like a nice to have request. The projects that really need it will be able to cover the improvement efforts. So, as soon as somebody is ready to support this improvement by money we will move on.  

For now if two or more simultaneous recording sessions are required it's possible to setup two or separate environments.
