### ISSUE TITLE
Recording fails

### ISSUE THREAD

**Issue by nukulyadav** [jelastic-jps/jitsi#16]
Hi,

The stack works fine with 1 Jibri, but if I set more than 2 Jibri using compose then it doesn't work.

 docker-compose -f docker-compose.yml -f jibri.yml  up -d --scale jibri=5

Basically only 1 Jibri work.

Can you fix that issue please?

Thanks

**Comment by sych74** [comment]
@nukulyadav, seems like it's not automated yet in the main Jitsi docker repo https://github.com/jitsi/docker-jitsi-meet/issues/372

**Comment by nukulyadav** [comment]
@sych74 Got that, But that's where the opportunity is. Officially Jibri should be installed in separate machine/container http://prntscr.com/wmaeyw [/jitsi/jibri](https://github.com/jitsi/jibri)

The scaling problem (with auto-horizontal) can be taken care if Jelastic provides a standalone Jibri which can connect to Jitsi on another machine.

That would resolve a big problem and would generate huge business for Jelastic as well as partners.

**Comment by sych74** [comment]
If there is a real big problem than somebody should be ready to pay for solving this problem. So in other words, if a service provider or an end customer is ready to cover the development cost we can talk more seriously about it.

**Comment by nukulyadav** [comment]
@sych74 Can you estimate the cost for this ?
