### ISSUE TITLE
Impossible to start a session

### ISSUE THREAD

**Issue by shirokoweb** [jelastic-jps/jitsi#7]
Impossible to start a session from environment-xxxx.{{hoster_domain}}
![image](https://user-images.githubusercontent.com/6638982/79328732-d3582a00-7f16-11ea-8e51-f81d6aede52d.png)

From docker Node https://docker64009-env-xxxx.{{hoster_domain}}
Session starts, but not secure and you gets disconnected every 30sec and you don't see anybody.
![image](https://user-images.githubusercontent.com/6638982/79329248-bf60f800-7f17-11ea-8c28-bf7c26278471.png)

**Comment by sych74** [comment]
@shirokoweb, what are the steps to reproduce?

**Comment by shirokoweb** [comment]
Step 1. Open Marketplace and deploy environment
![image](https://user-images.githubusercontent.com/6638982/79330427-cd177d00-7f19-11ea-951f-db62f3c7dffd.png)

Step 2. Open in Browser (Environment)
![image](https://user-images.githubusercontent.com/6638982/79330656-35fef500-7f1a-11ea-8f59-068da340bba0.png)

Step 3. Create a new meeting "room"
![image](https://user-images.githubusercontent.com/6638982/79330836-79596380-7f1a-11ea-8835-0e106cb2e802.png)

Step 4. Join the room:
![image](https://user-images.githubusercontent.com/6638982/79330904-99892280-7f1a-11ea-9b6b-72f196235e4e.png)

### Alt steps

Step 2.1. Open in Browser (Node)
![image](https://user-images.githubusercontent.com/6638982/79331030-d2c19280-7f1a-11ea-91a1-cd622f2f6f32.png)

Step 3.1. create a new meeting "room"
![image](https://user-images.githubusercontent.com/6638982/79331213-216f2c80-7f1b-11ea-8f38-27e144e00601.png)

Step 4.1 Join the room:
You can't see anybody + you get disconnected every 30 / 60 sec.
![image](https://user-images.githubusercontent.com/6638982/79331319-42378200-7f1b-11ea-91a9-d0a78857150d.png)

**Comment by sych74** [comment]
This looks strange as Jitsi jps package should not be available in the marketplace as it was not released yet. So, I believe you have an outdated version there. At the moment you can use [Import](https://docs.jelastic.com/environment-import) button and specify path to the [manifest](https://github.com/jelastic-jps/jitsi/blob/master/manifest.yaml).

**Comment by shirokoweb** [comment]
@sych74 Thanks, will give it a try and let you know.

**Comment by sych74** [comment]
Closing the issue. Let me know if issue still appears.
